.format.model.names <- cbind(
  
  c("aov","ANOVA",""), 
  c("arima","ARIMA",""), 
  c("Arima","ARIMA",""), 
  c("blogit","bivariate","logistic"),
  c("bprobit","bivariate","probit"), 
  c("betareg", "beta",""), 
  c("chopit","compound hierarchical","ordered probit"),
  c("clm","cumulative","link"), 
  c("censReg", "censored", "regression"), 
  c("cloglog.net","network compl.","log log"), 
  c("clogit","conditional","logistic"), 
  c("coxph","Cox","prop. hazards"),
  c("dynlm","dynamic","linear"), 
  c("lagsarlm","spatial","autoregressive"), 
  c("errorsarlm","spatial","error"),
  c("ei.dynamic","Quinn dynamic","ecological inference"), 
  c("ei.hier","$2 \times 2$ hierarchical","ecological inference"),
  c("ei.RxC","hierarchical multinominal-Dirichlet","ecological inference"), 
  c("exp","exponential",""), 
  c("ergm","exponential family","random graph"),
  c("factor.bayes","Bayesian","factor analysis"), 
  c("factor.mix","mixed data","factor analysis"),
  c("factor.ord","ordinal data","factor analysis"), 
  c("fGARCH","GARCH",""), c("gamma","gamma",""),
  c("gamma.gee","gamma generalized","estimating equation"), 
  c("gamma.mixed","mixed effects","gamma"),
  c("gamma.net","network","gamma"), 
  c("gamma.survey","survey-weighted","gamma"), 
  c("glmrob","robust","GLM"), 
  c("gls","generalized","least squares"),
  c("gmm","GMM",""),
  c("rem.dyad", "relational", "event (dyadic)"),
  c("irt1d","IRT","(1-dim.)"), 
  c("irtkd","IRT","(k-dim.)"),
  c("logit","logistic",""), 
  c("logit.bayes","Bayesian","logistic"),
  c("logit.gam","GAM","(logistic)"), 
  c("logit.gee","logistic generalized","estimating equation"),
  c("logit.mixed","mixed effects","logistic"), 
  c("logit.net","network","logistic"),
  c("logit.survey","survey-weighted","logistic"), 
  c("lognorm","log-normal",""),
  c("lmer","linear","mixed-effects"), c("glmer","generalized linear","mixed-effects"), c("nlmer","non-linear","mixed-effects"),
  c("ls","OLS",""), c("ls.mixed","mixed effect","linear"), c("lme","linear","mixed effects"), c("lmrob","MM-type","linear"),
  c("ls.net","network","least squares"), c("mlogit","multinomial","logistic"), c("mnlogit","multinomial","logit"),
  c("mlogit.bayes","Bayesian","multinomial logistic"), 
  c("negbin","negative","binomial"), c("normal","normal",""),
  c("multinom","multinomial log-linear","(neural networks)"), 
  c("nlme","non-linear","mixed effects"),
  c("normal.bayes","Bayesian","normal"), 
  c("normal.gam","GAM","(continuous)"),
  c("normal.gee","normal generalized","estimating equation"), 
  c("normal.net","network","normal"),
  c("normal.survey","survey-weighted","normal"), 
  c("ologit","ordered","logistic"),
  c("oprobit","ordered","probit"), 
  c("oprobit.bayes","Bayesian","ordered probit"),
  c("pmg","mean","groups"), 
  c("poisson","Poisson",""), 
  c("poisson.bayes","Bayesian","Poisson"),
  c("poisson.gam","GAM","(count)"), 
  c("poisson.mixed","mixed effects","Poisson"),
  c("poisson.survey","survey-weighted","Poisson"), 
  c("poisson.gee","Poisson generalized","estimation equation"),
  c("probit","probit",""), 
  c("probit.bayes","Bayesian","probit"),
  c("probit.gam","GAM","(probit)"), 
  c("probit.gee","probit generalized","estimating equation"),
  c("probit.mixed","mixed effects","probit"), 
  c("probit.net","network","probit"),
  c("probit.survey","survey-weighted","probit"), 
  c("relogit","rare events","logistic"),
  c("rq","quantile","regression"),
  c("rlm","robust","linear"), 
  c("sur","SUR",""), 
  c("threesls","3SLS",""),
  c("tobit","Tobit",""), 
  c("tobit(AER)","Tobit",""), 
  c("tobit.bayes","Bayesian","Tobit"),
  c("twosls","2SLS",""), 
  c("weibull","Weibull",""),
  c("zeroinfl","zero-inflated","count data"), 
  c("hurdle","hurdle",""),
  c("plm","panel","linear"),
  c("pgmm","panel","GMM"), 
  c("ivreg","instrumental","variable"),
  c("coxreg","Cox",""), 
  c("mlreg","ML","prop. hazards"), 
  c("weibreg","Weibull",""),
  c("aftreg","accelerated"," failure time"), 
  c("phreg","parametric","prop. hazards"),
  c("bj","Buckley-James",""), 
  c("cph","Cox",""), 
  c("Gls","generalized","least squares"), 
  c("lrm","logistic",""),
  c("ols","OLS",""), 
  c("psm","parametric","survival"), 
  c("Rq","quantile","regression"),
  c("hetglm","heteroskedastic","GLM"), 
  c("coeftest","coefficient","test"),
  c("heckit","Heckman","selection"), 
  c("selection","selection",""),
  c("probit.ss","probit",""), 
  c("binaryChoice","binary","choice"),
  c("brglm","GLM","(bias reduction)"), 
  c("maBina","binary model","(marginal effect)"),
  c("mclogit","mixed","conditional logit")

)
